version: '3'

services:
  redis:
    image: redis:6.2.13
    container_name: zerosx_redis_v6.2.13
    restart: always
    ports:
      - "6479:6379"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - ./conf:/redis/config
      # 数据文件
      - ./data/:/data/
    command: "redis-server /redis/config/redis.conf"
    privileged: true
    #network_mode: "host"