spring:

  datasource:
    url: jdbc:mysql://120.79.152.222:3306/zerosx_order?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: javax@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

zerosx:
  tenant:
    enable: false
    ignoreTables:
      - t_order
      - undo_log
    ignoreSqls: