#docker-compose --compatibility -f docker-compose-service.yaml up -d
version: '3'

services:
  #网关服务
  zerosx-gateway:
    image: registry.cn-shenzhen.aliyuncs.com/zerosx-cloud/zerosx-gateway:0.0.1
    container_name: zerosx-gateway
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "9100:9100"
    volumes:
      # 配置文件
      - /home/zerosx-cloud/logs/:/home/zerosx-cloud/logs/
  #认证服务
  zerosx-sas:
    image: registry.cn-shenzhen.aliyuncs.com/zerosx-cloud/zerosx-sas:0.0.3
    container_name: zerosx-sas
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "19108:19108"
    volumes:
      # 配置文件
      - /home/zerosx-cloud/logs/:/home/zerosx-cloud/logs/
  #系统服务
  zerosx-system:
    image: registry.cn-shenzhen.aliyuncs.com/zerosx-cloud/zerosx-system:0.0.1
    container_name: zerosx-system
    # 限制CPU及内存
    deploy:
      resources:
        limits:
          memory: 400M
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "19102:19102"
    volumes:
      # 配置文件
      - /home/zerosx-cloud/logs/:/home/zerosx-cloud/logs/
  #资源服务
  zerosx-resource:
    image: registry.cn-shenzhen.aliyuncs.com/zerosx-cloud/zerosx-resource:0.0.1
    container_name: zerosx-resource
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "19106:19106"
    volumes:
      # 配置文件
      - /home/zerosx-cloud/logs/:/home/zerosx-cloud/logs/
  #监控服务
#  zerosx-monitor:
#    image: registry.cn-shenzhen.aliyuncs.com/zerosx-cloud/zerosx-monitor:0.0.1
#    container_name: zerosx-monitor
#    environment:
#      # 时区上海
#      TZ: Asia/Shanghai
#    ports:
#      - "19120:19120"
#    volumes:
#      # 配置文件
#      - /home/zerosx-cloud/logs/:/home/zerosx-cloud/logs/
  #zerosx-ui
  zerosx-ui:
    image: registry.cn-shenzhen.aliyuncs.com/zerosx-cloud/zerosx-vue2:0.0.3
    container_name: zerosx-vue2
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "80:80"