version: '3'

services:
  #网关服务
  zerosx-gateway:
    image: registry.cn-shenzhen.aliyuncs.com/zeros-cloud/zerosx-gateway:0.0.1
    container_name: zerosx-gateway
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "9100:9100"
    volumes:
      # 配置文件
      - /home/zerosx-cloud/logs/:/home/zerosx-cloud/logs/
  #认证服务
  zerosx-auth:
    image: registry.cn-shenzhen.aliyuncs.com/zeros-cloud/zerosx-auth:0.0.1
    container_name: zerosx-auth
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "19101:19101"
    volumes:
      # 配置文件
      - /home/zerosx-cloud/logs/:/home/zerosx-cloud/logs/
  #系统服务
  zerosx-system:
    image: registry.cn-shenzhen.aliyuncs.com/zeros-cloud/zerosx-system:0.0.1
    container_name: zerosx-system
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "19102:19102"
    volumes:
      # 配置文件
      - /home/zerosx-cloud/logs/:/home/zerosx-cloud/logs/
  #监控服务
  zerosx-monitor:
    image: registry.cn-shenzhen.aliyuncs.com/zeros-cloud/zerosx-monitor:0.0.1
    container_name: zerosx-monitor
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "19120:19120"
    volumes:
      # 配置文件
      - /home/zerosx-cloud/logs/:/home/zerosx-cloud/logs/
  #zerosx-ui
  zerosx-ui:
    image: registry.cn-shenzhen.aliyuncs.com/zeros-cloud/zerosx-ui:0.0.1
    container_name: zerosx-ui
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "80:80"