spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://127.0.0.1:13306/zerosx_account?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: zerosx@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource

zerosx:
  tenant:
    enable: true
    ignoreTables:
      - t_account
      - undo_log
    ignoreSqls: