version: "3.1"
services:
  seata-server:
    image: seataio/seata-server:1.6.1
    container_name: zerosx_seata161
    #restart: unless-stopped
    restart: no
    ports:
      - "7091:7091"
      - "8091:8091"
    environment:
      - STORE_MODE=db
      # 以SEATA_IP作为host注册seata server
      - SEATA_IP=192.168.3.100
      - SEATA_PORT=8091
#      - JVM_XMX=512m
#      - JVM_XMS=512m
#      - JVM_XMN=256m
    volumes:
      #- "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"  #设置系统时区
      #- "/usr/share/zoneinfo/Asia/Shanghai:/etc/timezone"   #设置时区
      # 假设我们通过docker cp命令把资源文件拷贝到相对路径`./seata-server/resources`中
      # 如有问题，请阅读上面的[注意事项]以及[使用自定义配置文件]
      - "./seata-server/resources:/seata-server/resources"
      - "./logs:/root/logs"

# docker-compose --compatibility -f docker-compose.yaml up -d