spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://192.168.3.6:13306/zerosx_auth?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: zerosx@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource


logging:
  level:
    com.zerosx: debug


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# knife4j-openapi3
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false
  # 开启Swagger的Basic认证功能,默认是false
  # basic:
  #   enable: true
  #   # Basic认证用户名
  #   username: admin
  #   # Basic认证密码
  #   password: admin123

zerosx:
  tenant:
    enable: true
    ignoreTables:
      - oauth_client_details
      - undo_log
    ignoreSqls:
      