spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://127.0.0.1:13306/zerosx_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: zerosx@123456
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    com.zerosx: debug
    com.zerosx.encrypt2: error


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #关闭打印
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

zerosx:

  tenant:
    enable: true
    ignoreTables:
      - t_sys_menu
      - t_sys_role_menu
      - t_sys_user_role
      - t_sys_role_dept
      - t_sys_user_post
      - undo_log
    ignoreSqls:
      - com.zerosx.system.mapper.IMutiTenancyGroupMapper.selectTenancyExist
      - com.zerosx.system.mapper.ISysUserMapper.selectLoginSysUser
      - com.zerosx.system.mapper.ISysRoleMapper.selectRoleByUserId
      - com.zerosx.system.mapper.IMutiTenancyGroupMapper.selectTenancy
      - com.zerosx.system.mapper.ISysMenuMapper.findByRoleCodes

# knife4j-openapi3
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false
  # 开启Swagger的Basic认证功能,默认是false
  # basic:
  #   enable: true
  #   # Basic认证用户名
  #   username: admin
  #   # Basic认证密码
  #   password: admin123