
logging:
  level:
    com.zerosx: debug
    #com.zerosx.gateway.auth: info

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: zerosx-system
          uri: lb://zerosx-system
          predicates:
            - Path=/api-system/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

        - id: zerosx-resource
          uri: lb://zerosx-resource
          predicates:
            - Path=/api-resource/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
        - id: zerosx-auth
          uri: lb://zerosx-auth
          predicates:
            - Path=/api-auth/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
        #认证授权
        - id: oauth2-token
          uri: lb://zerosx-auth
          predicates:
            - Path=/oauth2/**
          filters:
            - PreserveHostHeader

        - id: zerosx-order
          uri: lb://zerosx-order
          predicates:
            - Path=/api-order/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
        - id: zerosx-stock
          uri: lb://zerosx-stock
          predicates:
            - Path=/api-stock/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

# #knife4j-openapi3
knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      enabled: true
      # 指定版本号(Swagger2|OpenAPI3)
      version : openapi3
      # 需要排除的微服务(eg:网关服务)
      excluded-services:
        - zerosx-gateway
        - seata-server